# Generated by Django 3.1.2 on 2020-10-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainFunc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionID', models.IntegerField()),
                ('content', models.CharField(max_length=10000)),
                ('UserID', models.IntegerField()),
                ('creditTime', models.DateTimeField(auto_now_add=True)),
                ('isBest', models.IntegerField(default=0)),
                ('image', models.ImageField(default='1.jpg', upload_to='QA_images')),
            ],
            options={
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='bookInfo',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='暂未确定', max_length=50)),
                ('Author', models.CharField(default='未知', max_length=20)),
                ('GradeUp', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('GradeDown', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('image', models.ImageField(default='1.jpg', upload_to='book_images')),
                ('Price', models.DecimalField(decimal_places=3, default=999.99, max_digits=5)),
                ('Discount', models.DecimalField(decimal_places=0, default=0.8, max_digits=3)),
            ],
            options={
                'db_table': 'bookInfo',
            },
        ),
        migrations.CreateModel(
            name='bookscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookID', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'bookscore',
            },
        ),
        migrations.CreateModel(
            name='bookSell',
            fields=[
                ('sellID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='1.jpg', upload_to='book_images')),
            ],
            options={
                'db_table': 'bookSell',
            },
        ),
        migrations.CreateModel(
            name='bookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookID', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('tag', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bookTag',
            },
        ),
        migrations.CreateModel(
            name='CatalogInData',
            fields=[
                ('InID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Variety', models.CharField(max_length=50)),
                ('Number', models.IntegerField()),
                ('Discount', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Payment', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Isclear', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CatalogInData',
            },
        ),
        migrations.CreateModel(
            name='CatalogOutData',
            fields=[
                ('OutID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Variety', models.CharField(max_length=50)),
                ('Number', models.IntegerField()),
                ('Discount', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Payment', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Isclear', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CatalogOutData',
            },
        ),
        migrations.CreateModel(
            name='informLetter',
            fields=[
                ('informID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('toUserID', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'informLetter',
            },
        ),
        migrations.CreateModel(
            name='letter',
            fields=[
                ('letterID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('From', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'letter',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('content', models.CharField(max_length=10000)),
                ('creditTime', models.DateTimeField(auto_now_add=True)),
                ('isFin', models.IntegerField(default=0)),
                ('image', models.ImageField(default='1.jpg', upload_to='QA_images')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='scoreToPresent',
            fields=[
                ('presentID', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('count', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='1.jpg', upload_to='gift_images')),
            ],
            options={
                'db_table': 'scoreToPresent',
            },
        ),
        migrations.CreateModel(
            name='SPbookpreorder',
            fields=[
                ('PrerderID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Variety', models.CharField(max_length=50)),
                ('Number', models.IntegerField()),
                ('Payment', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Isclear', models.IntegerField(default=0)),
                ('creditTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SPbookpreorder',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('openid', models.CharField(max_length=30)),
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='用户名未设置', max_length=20)),
                ('Phone', models.IntegerField()),
                ('image', models.ImageField(default='1.jpg', upload_to='user_images')),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('School', models.CharField(max_length=20)),
                ('classroom', models.IntegerField()),
                ('Credit', models.IntegerField(default=0)),
                ('FriendCredit', models.IntegerField(default=100)),
                ('Money', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'StudentInfo',
            },
        ),
        migrations.CreateModel(
            name='TeacherGradeInfo',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('Grade', models.IntegerField()),
            ],
            options={
                'db_table': 'TeacherGradeInfo',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('openid', models.CharField(max_length=30)),
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='用户名未设置', max_length=20)),
                ('Phone', models.IntegerField()),
                ('image', models.ImageField(default='1.jpg', upload_to='user_images')),
                ('School', models.CharField(default='请填写学校名称', max_length=20)),
                ('Credit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'TeacherInfo',
            },
        ),
        migrations.CreateModel(
            name='userArtical',
            fields=[
                ('ArticalID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=20000)),
                ('Author', models.IntegerField()),
            ],
            options={
                'db_table': 'userArtical',
            },
        ),
        migrations.CreateModel(
            name='Usergift',
            fields=[
                ('presentID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
            ],
            options={
                'db_table': 'Usergift',
            },
        ),
    ]
