# Generated by Django 3.1.2 on 2020-10-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0003_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='booksell',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scoretopresent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='image',
        ),
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='img',
            table='IMG',
        ),
    ]
