# Generated by Django 3.1.2 on 2020-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0004_auto_20201022_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
