# Generated by Django 3.1.2 on 2020-10-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0005_auto_20201023_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='Discount',
            field=models.DecimalField(decimal_places=3, default=0.8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='GradeDown',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='GradeUp',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=5),
        ),
        migrations.AlterField(
            model_name='catalogindata',
            name='Discount',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='catalogindata',
            name='Payment',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='catalogoutdata',
            name='Discount',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='catalogoutdata',
            name='Payment',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spbookpreorder',
            name='Payment',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Grade',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
