# Generated by Django 3.1.2 on 2020-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0006_auto_20201023_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='userOrder',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('commodityID', models.IntegerField()),
                ('commodityCount', models.IntegerField()),
            ],
            options={
                'db_table': 'userOrder',
            },
        ),
    ]
