# Generated by Django 3.1.2 on 2020-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0007_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='book_images'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='Discount',
            field=models.DecimalField(decimal_places=3, default=0.8, max_digits=4),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='GradeDown',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='GradeUp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
