# Generated by Django 3.1.2 on 2020-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0008_auto_20201024_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='GradeDown',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='GradeUp',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
